on: workflow_dispatch
jobs:
  publish:
    name: Publish uni
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pack
        working-directory: ./uni
        run: choco pack uni.nuspec
      - name: Set key
        env:
          CHOCO_TOKEN: ${{ secrets.CHOCO_TOKEN }}
        run: choco apikey add -k '${{ env.CHOCO_TOKEN }}' -s https://push.chocolatey.org/
      - name: Push
        run: choco push
